import 'the-new-css-reset/css/reset.css'
import '@/styles/style.scss'

import { notoSansJP } from '@/libs/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={notoSansJP.variable}>{children}</body>
    </html>
  )
}

export default RootLayout
