import 'the-new-css-reset/css/reset.css'
import '@/styles/globals.css'
import '@/styles/variables.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="ja">
      <body>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
